#!/bin/bash
set -euo pipefail

# shellcheck disable=SC1091
source .valheim.env

docker build \
  --target=bookworm-base \
  --build-arg VALHEIM_BUILD_ID="${VALHEIM_BUILD_ID}" \
  --build-arg VALHEIM_LINUX_DEPOT_MANIFEST_ID="${VALHEIM_LINUX_DEPOT_MANIFEST_ID}" \
  --build-arg VALHEIM_SHARED_LINUX_DEPOT_MANIFEST_ID="${VALHEIM_SHARED_LINUX_DEPOT_MANIFEST_ID}" \
  -t martingwheeler/valheim:latest \
  -t martingwheeler/valheim:base \
  --no-cache .
docker build --target=bookworm-plus \
  --build-arg VALHEIM_BUILD_ID="${VALHEIM_BUILD_ID}" \
  --build-arg VALHEIM_LINUX_DEPOT_MANIFEST_ID="${VALHEIM_LINUX_DEPOT_MANIFEST_ID}" \
  --build-arg VALHEIM_SHARED_LINUX_DEPOT_MANIFEST_ID="${VALHEIM_SHARED_LINUX_DEPOT_MANIFEST_ID}" \
  --build-arg VALHEIM_PLUS_VERSION="${VALHEIM_PLUS_VERSION}" \
  -t martingwheeler/valheim:plus \
  --no-cache .
