#!/bin/bash
set -euo pipefail

if [ "$(id -u)" = "0" ]; then
  mkdir -p "${SERVER_DIR}" "${CONTAINER_HOME}"
  chown -R "${PUID}:${PGID}" "${SERVER_DIR}" "${CONTAINER_HOME}"
  exec su-exec "${PUID}:${PGID}" /usr/local/bin/entry.sh
fi

mkdir -p "${SERVER_DIR}"
cd "${SERVER_DIR}"

if [ "${EULA}" != "TRUE" ] && [ "${EULA}" != "true" ]; then
  echo "You must accept the Minecraft EULA by setting EULA=TRUE" >&2
  echo "See https://aka.ms/MinecraftEULA" >&2
  exit 1
fi

cat > eula.txt <<EOF
# Generated by entry.sh
eula=true
EOF

if [ ! -f server.properties ]; then
  cat > server.properties <<EOF
# Generated by entry.sh on first start
enable-command-block=${ENABLE_COMMAND_BLOCK}
difficulty=${DIFFICULTY}
gamemode=${GAMEMODE}
level-name=${LEVEL_NAME}
max-players=${MAX_PLAYERS}
motd=${MOTD}
online-mode=${ONLINE_MODE}
server-port=${SERVER_PORT}
simulation-distance=${SIMULATION_DISTANCE}
view-distance=${VIEW_DISTANCE}
EOF
fi

echo "Starting PaperMC ${MINECRAFT_VERSION} build ${PAPER_BUILD}..."

cmd=(java "-Xms${MEMORY}" "-Xmx${MEMORY}")

if [ -n "${JAVA_OPTS}" ]; then
  # shellcheck disable=SC2206
  cmd+=( ${JAVA_OPTS} )
fi

cmd+=(-jar /opt/papermc/paper.jar --nogui)

if [ -n "${ADDITIONAL_ARGS}" ]; then
  # shellcheck disable=SC2206
  cmd+=( ${ADDITIONAL_ARGS} )
fi

exec "${cmd[@]}"
