#!/bin/bash
set -euo pipefail

write_jvm_args_file() {
  if [ -z "${JVM_ARGS_FILE:-}" ]; then
    return 0
  fi

  {
    printf '%s\n' "-Xms${MEMORY}"
    printf '%s\n' "-Xmx${MEMORY}"

    if [ -n "${JAVA_OPTS}" ]; then
      # shellcheck disable=SC2206
      local java_opts_array=( ${JAVA_OPTS} )
      printf '%s\n' "${java_opts_array[@]}"
    fi
  } > "${JVM_ARGS_FILE}"
}

if [ "$(id -u)" = "0" ]; then
  mkdir -p "${SERVER_DIR}" "${CONTAINER_HOME}"
  chown -R "${PUID}:${PGID}" "${SERVER_DIR}" "${CONTAINER_HOME}"
  exec su-exec "${PUID}:${PGID}" /usr/local/bin/entry.sh
fi

mkdir -p "${SERVER_DIR}"
cd "${SERVER_DIR}"

if [ "${EULA}" != "TRUE" ] && [ "${EULA}" != "true" ]; then
  echo "You must accept the Minecraft EULA by setting EULA=TRUE" >&2
  echo "See https://aka.ms/MinecraftEULA" >&2
  exit 1
fi

cat > eula.txt <<EOF
# Generated by entry.sh
eula=true
EOF

if [ ! -f server.properties ]; then
  cat > server.properties <<EOF
# Generated by entry.sh on first start
enable-command-block=${ENABLE_COMMAND_BLOCK}
difficulty=${DIFFICULTY}
force-gamemode=${FORCE_GAMEMODE}
gamemode=${GAMEMODE}
hardcore=${HARDCORE}
level-name=${LEVEL_NAME}
level-seed=${LEVEL_SEED}
level-type=${LEVEL_TYPE}
max-players=${MAX_PLAYERS}
max-build-height=${MAX_BUILD_HEIGHT}
motd=${MOTD}
online-mode=${ONLINE_MODE}
pvp=${PVP}
server-port=${SERVER_PORT}
simulation-distance=${SIMULATION_DISTANCE}
spawn-protection=${SPAWN_PROTECTION}
view-distance=${VIEW_DISTANCE}
white-list=${WHITE_LIST}
EOF
fi

version_label="Minecraft ${MINECRAFT_VERSION}"

if [ -n "${SERVER_SOFTWARE_VERSION:-}" ]; then
  version_label="${version_label} (${SERVER_SOFTWARE} ${SERVER_SOFTWARE_VERSION})"
else
  version_label="${version_label} (${SERVER_SOFTWARE})"
fi

echo "Starting ${version_label}..."

case "${SERVER_LAUNCH_MODE}" in
  jar)
    cmd=(java "-Xms${MEMORY}" "-Xmx${MEMORY}")

    if [ -n "${JAVA_OPTS}" ]; then
      # shellcheck disable=SC2206
      cmd+=( ${JAVA_OPTS} )
    fi

    cmd+=(-jar "${SERVER_EXECUTABLE}")

    if [ -n "${SERVER_NOGUI_FLAG:-}" ]; then
      cmd+=("${SERVER_NOGUI_FLAG}")
    fi
    ;;
  script)
    write_jvm_args_file
    cmd=("${SERVER_EXECUTABLE}")
    ;;
  *)
    echo "Unsupported SERVER_LAUNCH_MODE: ${SERVER_LAUNCH_MODE}" >&2
    exit 1
    ;;
esac

if [ -n "${ADDITIONAL_ARGS}" ]; then
  # shellcheck disable=SC2206
  cmd+=( ${ADDITIONAL_ARGS} )
fi

exec "${cmd[@]}"
